"""initial migration

Revision ID: 26701793b4ae
Revises: 
Create Date: 2025-07-08 01:30:17.886896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26701793b4ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    #op.drop_index(op.f('name'), table_name='tasks')
    # Drop foreign key first
   # op.drop_constraint('reports_ibfk_1', 'reports', type_='foreignkey')

# Then drop the task table
    #op.drop_table('task')
    op.drop_table('project_user')
    op.alter_column('project', 'name',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('project', 'manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.drop_constraint(op.f('reports_ibfk_1'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'tasks', ['task_id'], ['id'])
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    #op.drop_index(op.f('end_date'), table_name='task')
    #op.drop_index(op.f('start_date'), table_name='task')
    op.create_index(op.f('ix_task_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.create_index(op.f('start_date'), 'task', ['start_date'], unique=True)
    op.create_index(op.f('end_date'), 'task', ['end_date'], unique=True)
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_ibfk_1'), 'reports', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.alter_column('project', 'manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('project', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
    op.create_table('project_user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('project_user_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('project_user_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tasks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('tasks_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'tasks', ['name'], unique=True)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###
