"""Sync DB: ensure no duplicate operations

Revision ID: 7a67a4d19a9c
Revises: 26701793b4ae
Create Date: 2025-07-09 19:00:46.460513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a67a4d19a9c'
down_revision: Union[str, Sequence[str], None] = '26701793b4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tasks', ['name'])
    op.create_foreign_key(None, 'user', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='unique')
    # ### end Alembic commands ###
