"""Fix: Added length to task_name

Revision ID: fa2f83508605
Revises: 300aed5ef478
Create Date: 2025-07-09 22:40:03.514243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2f83508605'
down_revision: Union[str, Sequence[str], None] = '300aed5ef478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_tasks_id'), 'user_tasks', ['id'], unique=False)
    op.drop_constraint(op.f('user_tasks_ibfk_2'), 'user_tasks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_tasks_ibfk_2'), 'user_tasks', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_user_tasks_id'), table_name='user_tasks')
    # ### end Alembic commands ###
